import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const source = resolve("openapi.json");
const target = resolve("packages/api-client/src/generated/openapi.json");
const routesTarget = resolve("packages/api-client/src/generated/routes.ts");
const clientTarget = resolve("packages/api-client/src/generated/client.ts");

mkdirSync(dirname(target), { recursive: true });
if (existsSync(source)) {
  copyFileSync(source, target);
} else {
  writeFileSync(target, "{}\n");
}

const openapi = existsSync(source) ? JSON.parse(readFileSync(source, "utf8")) as { paths?: Record<string, unknown> } : { paths: {} };
const paths = Object.keys(openapi.paths ?? {});
type Method = "get" | "post" | "patch" | "delete";

function methodsFor(path: string): Method[] {
  const item = (openapi.paths?.[path] ?? {}) as Record<string, unknown>;
  return (Object.keys(item) as Method[]).filter((method) => ["get", "post", "patch", "delete"].includes(method));
}

function operationKey(method: Method, path: string): string {
  return `${method.toUpperCase()} ${path}`;
}

function routeKey(path: string): string {
  return path
    .replace("/v1/", "")
    .replace("/", "")
    .replaceAll("/", "_")
    .replaceAll("-", "_")
    .replace(/[{}]/g, "")
    .replace(/\W/g, "_") || "root";
}

function methodName(method: Method, path: string): string {
  const parts = routeKey(path).split("_").filter(Boolean);
  const pascal = parts.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join("");
  return `${method}${pascal}`;
}

function responseType(method: Method, path: string): string {
  const key = operationKey(method, path);
  if (key === "GET /v1/session/current") return "CurrentSession";
  if (key === "POST /v1/session/accept-invitation") return "CurrentSession";
  return "unknown";
}

function requestType(method: Method, path: string): string | null {
  const key = operationKey(method, path);
  if (key === "POST /v1/session/accept-invitation") return "{ token: string }";
  const item = (openapi.paths?.[path] ?? {}) as Record<string, any>;
  return item[method]?.requestBody ? "unknown" : null;
}

const entries = paths
  .map((path) => {
    return `  ${JSON.stringify(routeKey(path))}: ${JSON.stringify(path)}`;
  });

writeFileSync(routesTarget, `// Generated by packages/api-client/src/generate.ts from openapi.json.
export const generatedRoutes = {
${entries.join(",\n")}
} as const;
`);

const operations = paths.flatMap((path) => methodsFor(path).map((method) => ({ path, method })));
const operationEntries = operations.map(({ path, method }) => {
  const request = requestType(method, path);
  const requestPart = request ? ` request: ${request};` : "";
  return `  ${JSON.stringify(operationKey(method, path))}: {${requestPart} response: ${responseType(method, path)} };`;
});

const operationMethods = operations.map(({ path, method }) => {
  const name = methodName(method, path);
  const key = operationKey(method, path);
  const request = requestType(method, path);
  const route = `generatedRoutes[${JSON.stringify(routeKey(path))}]`;
  const httpMethod = method.toUpperCase();
  if (method === "get" && !request) {
    return `  ${name}(): Promise<GeneratedOperationMap[${JSON.stringify(key)}]["response"]> {
    return this.request(${route});
  }`;
  }
  return `  ${name}(body${request ? `: GeneratedOperationMap[${JSON.stringify(key)}]["request"]` : "?: never"}): Promise<GeneratedOperationMap[${JSON.stringify(key)}]["response"]> {
    const init: RequestInit = {
      method: ${JSON.stringify(httpMethod)},
      headers: { "content-type": "application/json" }
    };
    if (body !== undefined) init.body = JSON.stringify(body);
    return this.request(${route}, init);
  }`;
});

writeFileSync(clientTarget, `// Generated by packages/api-client/src/generate.ts from openapi.json.
import type { CurrentSession } from "@ctw/contracts";
import { generatedRoutes } from "./routes.js";

export type GeneratedOperationMap = {
${operationEntries.join("\n")}
};

export type GeneratedApiClientOptions = {
  baseUrl?: string;
  fetchImpl?: typeof fetch;
};

export class GeneratedApiClient {
  private readonly baseUrl: string;
  private readonly fetchImpl: typeof fetch;

  constructor(options: GeneratedApiClientOptions = {}) {
    this.baseUrl = options.baseUrl ?? "";
    this.fetchImpl = options.fetchImpl ?? fetch;
  }

  private async request<T>(path: string, init?: RequestInit): Promise<T> {
    const response = await this.fetchImpl(\`\${this.baseUrl}\${path}\`, init);
    if (!response.ok) throw new Error(\`API request failed: \${response.status}\`);
    return response.json() as Promise<T>;
  }

${operationMethods.join("\n\n")}
}

export const apiClient = new GeneratedApiClient();
`);
