import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const source = resolve("openapi.json");
const target = resolve("packages/api-client/src/generated/openapi.json");
const routesTarget = resolve("packages/api-client/src/generated/routes.ts");
const clientTarget = resolve("packages/api-client/src/generated/client.ts");

mkdirSync(dirname(target), { recursive: true });
if (existsSync(source)) {
  copyFileSync(source, target);
} else {
  writeFileSync(target, "{}\n");
}

const openapi = existsSync(source) ? JSON.parse(readFileSync(source, "utf8")) as { paths?: Record<string, unknown> } : { paths: {} };
const paths = Object.keys(openapi.paths ?? {});
const entries = paths
  .filter((path) => path.startsWith("/v1/"))
  .map((path) => {
    const key = path
      .replace("/v1/", "")
      .replaceAll("/", "_")
      .replaceAll("-", "_")
      .replace(/[{}]/g, "")
      .replace(/\W/g, "_");
    return `  ${JSON.stringify(key)}: ${JSON.stringify(path)}`;
  });

writeFileSync(routesTarget, `// Generated by packages/api-client/src/generate.ts from openapi.json.
export const generatedRoutes = {
${entries.join(",\n")}
} as const;
`);

const hasCurrentSession = paths.includes("/v1/session/current");
const hasAcceptInvitation = paths.includes("/v1/session/accept-invitation");

writeFileSync(clientTarget, `// Generated by packages/api-client/src/generate.ts from openapi.json.
import type { CurrentSession } from "@ctw/contracts";
import { generatedRoutes } from "./routes.js";

export type GeneratedOperationMap = {
${hasCurrentSession ? `  "GET /v1/session/current": { response: CurrentSession };` : ""}
${hasAcceptInvitation ? `  "POST /v1/session/accept-invitation": { request: { token: string }; response: CurrentSession };` : ""}
};

export type GeneratedApiClientOptions = {
  baseUrl?: string;
  fetchImpl?: typeof fetch;
};

export class GeneratedApiClient {
  private readonly baseUrl: string;
  private readonly fetchImpl: typeof fetch;

  constructor(options: GeneratedApiClientOptions = {}) {
    this.baseUrl = options.baseUrl ?? "";
    this.fetchImpl = options.fetchImpl ?? fetch;
  }

  private async request<T>(path: string, init?: RequestInit): Promise<T> {
    const response = await this.fetchImpl(\`\${this.baseUrl}\${path}\`, init);
    if (!response.ok) throw new Error(\`API request failed: \${response.status}\`);
    return response.json() as Promise<T>;
  }

${hasCurrentSession ? `  getCurrentSession(): Promise<GeneratedOperationMap["GET /v1/session/current"]["response"]> {
    return this.request(generatedRoutes["session_current"]);
  }` : ""}

${hasAcceptInvitation ? `  acceptInvitation(body: GeneratedOperationMap["POST /v1/session/accept-invitation"]["request"]): Promise<GeneratedOperationMap["POST /v1/session/accept-invitation"]["response"]> {
    return this.request(generatedRoutes["session_accept_invitation"], {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(body)
    });
  }` : ""}
}

export const apiClient = new GeneratedApiClient();
`);
