import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const source = resolve("openapi.json");
const target = resolve("packages/api-client/src/generated/openapi.json");
const routesTarget = resolve("packages/api-client/src/generated/routes.ts");

mkdirSync(dirname(target), { recursive: true });
if (existsSync(source)) {
  copyFileSync(source, target);
} else {
  writeFileSync(target, "{}\n");
}

const openapi = existsSync(source) ? JSON.parse(readFileSync(source, "utf8")) as { paths?: Record<string, unknown> } : { paths: {} };
const paths = Object.keys(openapi.paths ?? {});
const entries = paths
  .filter((path) => path.startsWith("/v1/"))
  .map((path) => {
    const key = path
      .replace("/v1/", "")
      .replaceAll("/", "_")
      .replaceAll("-", "_")
      .replace(/[{}]/g, "")
      .replace(/\W/g, "_");
    return `  ${JSON.stringify(key)}: ${JSON.stringify(path)}`;
  });

writeFileSync(routesTarget, `// Generated by packages/api-client/src/generate.ts from openapi.json.
export const generatedRoutes = {
${entries.join(",\n")}
} as const;
`);
